### ISSUE TITLE
Lich ritual not working

### ISSUE THREAD

**Issue by WPeanuts** [BloomhouseMC/Besmirchment#10]
The book states that, "Starting this ritual requires the lack of a soul, or in short terms, having the Apathy curse." it also states that "it will also require the sacrifice of a demonic entity." after setting the apathy curse up in the brazier, and then using at first a demon, but after several failed attempts I switched to greater demons (with no success)

**Comment by mrsterner** [comment]
You need to kill it with an athame

**Comment by WPeanuts** [comment]
thank you!
