### ISSUE TITLE
Add a way to transform into Lich and Werepyre with curses off

### ISSUE THREAD

**Issue by Sebas-Re** [BloomhouseMC/Besmirchment#11]
hello,

We currently have curses disabled on our server to avoid abuse, so we would like to know if you can perhaps add a way to transform into Lich and Werepyre with curses off (ex. you can still transform into bewitchment's Vampire and Werewolf even with curses off, you just skip that step). Perhaps just the rituals? ofc the mod would have to know if curses are enabled or disabled on server in order to allow skipping the self cursing step

**Comment by mrsterner** [comment]
Already possible, just do what you would normally do to reach lichdom/get infected

**Comment by Sebas-Re** [comment]
Thanks a lot!
