### ISSUE TITLE
[1.19.2] Issues related to the Curse of Apathy and Lichdom

### ISSUE THREAD

**Issue by EdoardoTessaro** [BloomhouseMC/Besmirchment#16]
If you suffer from the Curse of Apathy and try to use ME-consuming items, like the Juniper broom, the game crashes, giving an index out of bounds exception.

Also, after becoming a lich, if you successfully remove the Curse of Apathy with the Ritual of Cleansing (checking with the Crystal Ball, the curse is indeed gone), the ME bar reappears but never fills up, while constantly draining the altar to 0 ME; and if you attempt to ride a juniper broom in this situation, the index out of bounds crash still happens despite the curse being gone.

**Comment by EdoardoTessaro** [comment]
Some more details:
The first issue isn't actually a crash, but rather a "connection lost" error, so I can't provide a crashlog. Here's a screenshot.
![error](https://user-images.githubusercontent.com/9116394/204086867-3a74ae21-303c-447e-8afb-77297fd00135.png)

The ME issue resolves itself once you add souls to the phylactery, but only if you place it down after becoming a lich; if you place it before the ritual it doesn't seem to bind to the player

**Comment by Thepigcat76** [comment]
Have the same issue!
