### ISSUE TITLE
SpawnSmokeParticlesPacket signature change in latest bewitchment

### ISSUE THREAD

**Issue by Linguardium** [BloomhouseMC/Besmirchment#26]
https://github.com/BloomhouseMC/Besmirchment/blob/0160a86e8981736daaa8647ea501d2404d41fadf/src/main/java/dev/mrsterner/besmirchment/common/entity/WerepyreEntity.java#L54

https://mclo.gs/fLU60Mc

edit: my mistake, it was just modified https://github.com/MoriyaShiine/bewitchment/blob/master/src/main/java/moriyashiine/bewitchment/client/packet/SpawnSmokeParticlesPacket.java

Takes a ServerPlayerEntity now

**Comment by mrsterner** [comment]
fixed in 1.20.1-4
