### ISSUE TITLE
Server Stops loading due to tag error

### ISSUE THREAD

**Issue by Toilet-Lord** [BloomhouseMC/Besmirchment#5]
Was playing fine then restarted the server and now it can't lunch bc of this

> [18:03:25] [Worker-Main-4/ERROR]: Couldn't load tag besmirchment:illegal_familiar as it is missing following references: #bewitchment:untaglockable (from Besmirchment)

here the log file:
[2022-01-14-1.log](https://github.com/BloomhouseMC/Besmirchment/files/7873768/2022-01-14-1.log)

**Comment by mrsterner** [comment]
The server shouldnt stop because of a tag error, its probably something else that causes the crash, unrelated to besmirchment

**Comment by Toilet-Lord** [comment]
I did a very dumb thing which is deleting the .json that was causing the problem, I realise this might break the game even more but it works, for now
